name: Deploy Data Platform to Development Environment

on:
  push:
    branches:
      - dev-**                              # Toda branch que subir com este prefixo "dev-"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - uses: actions/setup-node@v2-beta      # Necessário para o cdk
      with:
        node-version: '12'

    - name: Install dependencies
      run: |
        sudo npm install -g aws-cdk
        pip install -r requirements.txt
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        ENVIRONMENT: DEVELOP
      run: |                              # * para fazer o deploy de todos os stacks do projeto e --require para não pedir aprovação do usuário.
        cdk deploy "*" --require-approval never
        